server:
  port: 8080

spring:
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:todo}
    username: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
